# frozen_string_literal: true

module ActiveCampaign
  class List < Model # :nodoc:
    define_attributes :stringid,
                      :userid,
                      :name,
                      :p_use_tracking,
                      :p_use_analytics_read,
                      :p_use_analytics_link,
                      :p_use_twitter,
                      :p_use_facebook,
                      :p_embed_image,
                      :p_use_captcha,
                      :send_last_broadcast,
                      :private,
                      :analytics_domains,
                      :analytics_source,
                      :analytics_ua,
                      :twitter_token,
                      :twitter_token_secret,
                      :facebook_session,
                      :carboncopy,
                      :subscription_notify,
                      :unsubscription_notify,
                      :require_name,
                      :get_unsubscribe_reason,
                      :to_name,
                      :optinoptout,
                      :sender_name,
                      :sender_addr1,
                      :sender_addr2,
                      :sender_city,
                      :sender_state,
                      :sender_zip,
                      :sender_country,
                      :sender_phone,
                      :sender_url,
                      :sender_reminder,
                      :fulladdress,
                      :optinmessageid,
                      :optoutconf,
                      :deletestamp,
                      :udate,
                      :user
  end
end
